# Generated by Django 4.1.2 on 2023-05-16 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_results_coursework'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursework',
            name='course_quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
        ),
    ]
