# Generated by Django 4.1.2 on 2023-05-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_coursework_course_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursework',
            name='the_classification',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='coursework',
            name='the_course',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coursework',
            name='the_remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
