# Generated by Django 4.1.2 on 2023-05-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quiz_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursework',
            name='course_quiz',
        ),
        migrations.AddField(
            model_name='coursework',
            name='course_quiz',
            field=models.ManyToManyField(null=True, to='quiz.quiz'),
        ),
    ]
