# Generated by Django 4.1.2 on 2022-12-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='books',
        ),
        migrations.AddField(
            model_name='course',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, to='courses.book'),
        ),
    ]
