# Generated by Django 4.1.2 on 2022-12-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='course',
            name='tutorial',
        ),
        migrations.AddField(
            model_name='course',
            name='assignment',
            field=models.ManyToManyField(blank=True, to='courses.assignment'),
        ),
        migrations.AddField(
            model_name='course',
            name='tutorial',
            field=models.ManyToManyField(blank=True, to='courses.video'),
        ),
    ]
