# Generated by Django 4.1.2 on 2022-12-26 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_submit_done_assignment_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='assignment',
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
