# Generated by Django 4.1.2 on 2023-01-14 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_submit_assignment_alter_submit_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='assignment',
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
