# Generated by Django 4.1.2 on 2023-02-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_registerdcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerdcourse',
            name='course',
        ),
        migrations.AddField(
            model_name='registerdcourse',
            name='course',
            field=models.ManyToManyField(to='courses.course'),
        ),
    ]
