# Generated by Django 4.1.2 on 2023-01-14 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UsersAuth', '0002_alter_news_options_comments_news_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-added']},
        ),
        migrations.RemoveField(
            model_name='news',
            name='comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UsersAuth.news'),
        ),
    ]
